# Generated by Django 5.0 on 2024-01-27 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompts_and_Responses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promptResponse",
                    models.CharField(
                        choices=[("prompt", "prompt"), ("response", "response")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chats.conversation",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="PromptResponse",),
    ]
