# Generated by Django 5.0 on 2024-01-27 23:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_prompts_and_responses_delete_promptresponse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation", old_name="client", new_name="client_name",
        ),
        migrations.RenameField(
            model_name="conversation",
            old_name="timestamp",
            new_name="created_timestamp",
        ),
        migrations.AddField(
            model_name="conversation",
            name="client_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
